version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile-python-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db