# Generated by Django 2.2.6 on 2019-11-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20191102_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceactivationlog',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webApp.Messages'),
        ),
        migrations.AlterField(
            model_name='temperaturemeasures',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='webApp.Messages'),
        ),
    ]
